name: cringe_miner
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dynamic_color: ^1.6.6
  firebase_core: ^2.15.1
  wolt_modal_sheet: ^0.1.2
  modal_bottom_sheet: ^3.0.0-pre
  firebase_auth: ^4.9.0
  firebase_database: ^10.2.5
  google_sign_in: ^6.1.5
  flutter_bounceable: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

main: lib/main.dart
